name: K6 load test

on:
  push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v3

      - name: step 2 - run k6 load test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: scripts/k6Aws.js

      - run: 
          ls
          mkdir report
          mv index.html report

      - name: step 3 - upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Relatorio de testes de performance
          path: report

      - name: step 4 - publish report
        uses: peaceiris/actions-gh-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: report
