name: K6 load test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 checkout
        uses: actions/checkout@v3

      - name: step 2 - run k6 load test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: scripts/k6Aws.js

      - run ls & mkdir report & mv index.html report

      - name: step 4 - upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Relatorio de testes de performance
          path: report